baseURL = "https://kelvin2dan.github.io"
languageCode = "zh-cn"
title = "Kelvin's Blog"
author = "Kelvin"

sectionPagesMenu = "main"

# # main menu
# [menu]
#     [[menu.main]]
#         identifier = "HomePage"
#         name = "Home"
#         url = "/"
#         weight = 1